.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH GYOTOY 1 "AUGUST 2011" Science "User Manuals"
.SH NAME
Gyotoy \- visualize one geodesic in Kerr metric
.SH SYNOPSIS
gyotoy [\fIinput.xml\fR]
.SH DESCRIPTION
Gyoto is a framework for computing geodesics in curved
space-times. The \fBgyotoy\fR utility program uses this framework to
compute and display a single geodesic (the trajectory of a massive or
mass-less particle) in Kerr metric.

\fBgyotoy\fR takes as optional argument a scenery description in XML
format (\fIinput.xml\fR). This scenery must contain a Astrobj section
of kind Star. Alternatively, a default scenery is loaded.

The user can then interactively select initial parameters and redraw
the geodesic as many time as needed. the Projection parameters allow
rotating the view and various menu entries are rather
self-explanatory. Entries in the File menu allow saving the display as
an image file, saving the parameters as an XML description, or saving
the geodesic's coordinates in an ASCII file.

\fBgyotoy\fR is only a small utility to visualise a single
geodesic. It can also be invoked from the \fByorick\fR(1) prompt for
building more complex graphics and for scripting. Have a look at the
gyoto.i and gyotoy.i files in \fByorick\fR's Y_SITE directory.

A companion program, \fBgyoto\fR(1), can be used to compute an entire
Gyoto scenery using relativistic ray-tracing.

.SH ENVIRONMENT
.IP GYOTO_PLUGINS
The "Star" object in Gyoto is part of the standard plug-in. If the
GYOTO_PLUGINS environment variable is set, it must contain at least
"stdplug" for \fBgyotoy\fR to run properly.
.SH AUTHOR
Thibaut Paumard <thibaut.paumard@obspm.fr> wrote this manual.
.SH "SEE ALSO"
.BR gyoto (1),
.BR yorick (1)
